name: 每日BTC技术指标报告

on:
  schedule:
    # 每天下午6点40分发送（北京时间）
    # UTC时间需要-8小时，所以：
    # 北京时间18:40 = UTC 10:40
    - cron: '40 10 * * *'   # 每天UTC 10:40（北京时间18:40）
  workflow_dispatch:  # 允许手动触发

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装Python依赖包
        run: |
          pip install --upgrade pip
          pip install pandas numpy yfinance requests
          # 使用预编译的TA-Lib wheel
          pip install --find-links https://github.com/TA-Lib/ta-lib-python/releases TA-Lib
      
      - name: 测试邮箱配置
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python3 "测试邮箱配置.py"
      
      - name: 测试主程序
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python3 "测试主程序.py"
      
      - name: 发送完整版BTC技术指标报告
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python3 "调试主程序.py"
      
      - name: 发送结果
        if: always()
        run: echo "邮件发送任务完成于 $(date)"