name: 每日BTC技术指标报告

on:
  schedule:
    # 每天下午2点50分发送（北京时间）
    # UTC时间需要-8小时，所以：
    # 北京时间14:50 = UTC 06:50
    - cron: '50 6 * * *'   # 每天UTC 6:50（北京时间14:50）
  workflow_dispatch:  # 允许手动触发

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装Python依赖包
        run: |
          pip install --upgrade pip
          pip install requests
      
      - name: 发送邮件
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python3 "云服务自动发送邮件.py"
      
      - name: 发送结果
        if: always()
        run: echo "邮件发送任务完成于 $(date)"