name: 每日BTC技术指标报告

on:
  schedule:
    # 每天早上8点发送（北京时间）
    # UTC时间需要-8小时，所以：
    # 北京时间08:00 = UTC 00:00
    - cron: '0 0 * * *'   # 每天UTC 00:00（北京时间08:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget
      
      - name: 安装TA-Lib
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
          sudo ldconfig
      
      - name: 安装Python依赖包
        run: |
          pip install --upgrade pip
          pip install pandas numpy yfinance requests TA-Lib
      
      - name: 发送完整版BTC技术指标报告
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python3 "【邮箱提示】指标提醒.py"
      
      - name: 发送结果
        if: always()
        run: echo "邮件发送任务完成于 $(date)"